meta_title: "Simplify"
meta_description: "Improve your consulting operations with Simplify."
meta_image: "logo_simplify.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@nomdevotrecompte" # indispensable pour les Twitter Cards
